---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "${SERVICE_NAME}"
  spec:
    ports:
    - name: "http"
      port: 8080
      targetPort: ${INTERNAL_PORT}
    selector:
      app.kubernetes.io/name: "${SERVICE_NAME}"
    type: "ClusterIP"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "${SERVICE_NAME}-management"
  spec:
    ports:
      - name: "management"
        port: 9000
        targetPort: ${MANAGEMENT_PORT}
    selector:
      app.kubernetes.io/name: "${SERVICE_NAME}"
    type: "ClusterIP"
- apiVersion: "apps.openshift.io/v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      app.openshift.io/runtime: "quarkus"
      app.kubernetes.io/name: "${SERVICE_NAME}"
    name: "${SERVICE_NAME}"
  spec:
    replicas: 1
    selector:
      app.kubernetes.io/name: "${SERVICE_NAME}"
    template:
      metadata:
        labels:
          app.openshift.io/runtime: "quarkus"
          app.kubernetes.io/name: "${SERVICE_NAME}"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "${IMAGE}"
          name: "${SERVICE_NAME}"
          ports:
            - containerPort: ${INTERNAL_PORT}
              name: "http"
              protocol: "TCP"
            - containerPort: ${MANAGEMENT_PORT}
              name: "management"
              protocol: "TCP"
